### ISSUE TITLE
Cannot read properties of null (reading 'culture') on pre-existing images

### ISSUE THREAD

**Issue by digbyswift-joe** [dawoe/umbraco-multilanguage-textbox#6]
Umbraco Version:  10.6.1
Package Version: 10.1.0

Currently experiencing an issue where the textboxes only intermittently appear when loading media items (we have implemented this field to produce Alt Text on an Image media type).

- If an Image item in the CMS is created from scratch, the field loads fine.
- If an existing image (uploaded prior to the package being installed) is loaded in the CMS, the field is empty (no textboxes are rendered).
- Saving that existing image (that was not showing the field) will result in the fields then being present after a reload.

![image](https://github.com/dawoe/umbraco-multilanguage-textbox/assets/92090919/7c469104-e7d2-4412-9d41-0d1c895e3784)

![image](https://github.com/dawoe/umbraco-multilanguage-textbox/assets/92090919/02d0150c-6fe2-48a1-a8eb-cc904561eaa4)

`umbraco-backoffice-js.js.v638261346957915838:147 TypeError: Cannot read properties of null (reading 'culture')
    at controller.js:97:25
    at lr (umbraco-backoffice-js.js.v638261346957915838:376:8515)
    at Function.br (umbraco-backoffice-js.js.v638261346957915838:376:9168)
    at controller.js:95:33
    at Function.mr (umbraco-backoffice-js.js.v638261346957915838:376:9283)
    at controller.js:86:10
    at umbraco-backoffice-js.js.v638261346957915838:159:454
    at m.$digest (umbraco-backoffice-js.js.v638261346957915838:171:67)
    at m.$apply (umbraco-backoffice-js.js.v638261346957915838:174:484)
    at k (umbraco-backoffice-js.js.v638261346957915838:125:445) 'Possibly unhandled rejection: {}'`

**Comment by digbyswift-joe** [comment]
Hi again. Just a message to give this a quick bump for visibility, and to see if there is any further information required to assist with this...

**Comment by dawoe** [comment]
Hi @digbyswift-joe 

Sorry for the late reply. I just tried to reproduce, but I don't get the error.

Steps I have taken.

1. Create a new site using the Starter Kit
2. Added several languages
3. Uploaded a image in the media library
4. Installed this package.
5. Created a datatype.
6. Added a property to the image media type
7. Go to the previously uploaded image

For me all the text boxes are displaying just fine

**Comment by digbyswift-joe** [comment]
@dawoe going to close this one due to the age of the issue, and that it has not been subsequently chased.

If it becomes an issue again I will get back in touch with further details, as the original versions mentioned are no longer relevant for our project.
